spring:
  application:
    name: ai-backend
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_platform
    username: root
    password: 123456
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      # 设置写入redis的key一小时后自动过期
      ttl: 3600
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
  # cookie 30 天过期
  session:
    cookie:
      max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: org.example.ai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <api-key>
      model-name: deepseek-chat
      # 请求及响应日志记录
      log-requests: true
      log-responses: true
      # 设置输出长度
      max-tokens: 8192
      # 确保以json格式输出
      strict-json-schema: true
      response-format: json_object
      # 出现问题时最大重试次数
      max-retries: 3
      # 流式模型
      streaming-chat-model:
        base-url: https://api.deepseek.com
        api-key: <api-key>
        model-name: deepseek-chat
        # 请求及响应日志记录
        log-requests: true
        log-responses: true
        # 设置输出长度
        max-tokens: 8192
        # 流式响应不支持结构化输出
        # 出现问题时最大重试次数
        max-retries: 3
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-shanghai
    bucket: your-bucket-name
