spring:
  application:
    name: ai-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_platform
    username: root
    password: 123456
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: org.example.ai.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <api-key>
      model-name: deepseek-chat
      # 请求及响应日志记录
      log-requests: true
      log-responses: true
      # 设置输出长度
      max-tokens: 8192
      # 确保以json格式输出
      strict-json-schema: true
      response-format: json_object
      # 出现问题时最大重试次数
      max-retries: 3
      # 流式模型
      streaming-chat-model:
        base-url: https://api.deepseek.com
        api-key: <api-key>
        model-name: deepseek-chat
        # 请求及响应日志记录
        log-requests: true
        log-responses: true
        # 设置输出长度
        max-tokens: 8192
        # 流式响应不支持结构化输出
        # 出现问题时最大重试次数
        max-retries: 3
